jobs:
  "Production Environment":
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "87:ba:54:2b:83:c2:d6:0d:4c:01:23:09:8d:cc:2a:95"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |
           echo "A first hello"
           ls --all
           pwd 
           echo "Finished"              
           scp -o StrictHostKeyChecking=no .circleci/production/index.html ubuntu@ec2-3-226-245-180.compute-1.amazonaws.com:/var/www/html

  "Development Environment":
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "87:ba:54:2b:83:c2:d6:0d:4c:01:23:09:8d:cc:2a:95"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |
           echo "A first hello"
           ls --all
           pwd 
           echo "Finished"              
           scp -o StrictHostKeyChecking=no .circleci/production/index.html ubuntu@ec2-3-219-35-180-compute-1.amazonaws.com:/var/www/html

workflows:
  version: 2
  build: 
    jobs:
      - "Production Environment"
      - "Development Environment"
      
                   
            


            

