jobs:
  ProductionEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "81:88:b3:35:ef:1b:a2:1d:5a:e8:bf:b6:12:7f:a4:54"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |
           echo "A first hello"
           ls --all
           pwd 
           echo "Finished new"              
           scp -o StrictHostKeyChecking=no .circleci/index.html ubuntu@3.219.35.180:/var/www/html/index.html

  DevelopmentEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "81:88:b3:35:ef:1b:a2:1d:5a:e8:bf:b6:12:7f:a4:54"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |
           echo "A first hello "
           ls --all
           pwd 
           echo "Finished new x2"              
           scp -o StrictHostKeyChecking=no .circleci/index.html ubuntu@3.226.245.180:/var/www/html/index.html

workflows:
  version: 2
  build: 
    jobs:
      - Production Environment:
      - Development Environment:
